// PDF Report Generator
// 基于用户选择的名字、场景生成带米字格的 PDF 报告

interface NameDetail {
  char: string;
  pinyin: string;
  meaning: string;
  etymology: string;
}

interface NameIdentity {
  id: string;
  characters: string;
  pinyin: string;
  englishMeaning: string;
  intent?: string;
  details: NameDetail[];
  culturalResonance: string;
  safetyAudit: {
    tattoo: string;
    business: string;
    digital: string;
  };
  mockups?: {
    calligraphy: string;
    seal: string;
    modern: string;
  };
}

interface ReportData {
  name: NameIdentity;
  goal: string;
  purchaseDate: string;
  orderId: string;
}

// 简化的 PDF 生成（实际项目需要使用 jsPDF 库）
export async function generateReportPDF(data: ReportData): Promise<Buffer> {
  const { name, goal, purchaseDate, orderId } = data;
  
  // 生成 PDF 内容的文本表示
  // 实际环境应使用 jsPDF 库生成真正的 PDF
  const content = generatePDFContent(data);
  
  // 转换为 Buffer
  return Buffer.from(content, 'utf-8');
}

function generatePDFContent(data: ReportData): string {
  const { name, goal, purchaseDate, orderId } = data;
  
  const strokeGrid = generateStrokeGrid(name.characters);
  
  return `
================================================================================
                           CINNABAR CHINESE NAME REPORT
================================================================================

ORDER INFORMATION
--------------------------------------------------------------------------------
Order ID: ${orderId}
Purchase Date: ${purchaseDate}
Primary Goal: ${goal}

================================================================================
                               YOUR CHINESE NAME
================================================================================

CHARACTER(S): ${name.characters}
PINYIN: ${name.pinyin}
ENGLISH MEANING: ${name.englishMeaning}

--------------------------------------------------------------------------------
                            CHARACTER BREAKDOWN
--------------------------------------------------------------------------------

${name.details.map((detail, i) => `
[Character ${i + 1}] ${detail.char}
Pinyin: ${detail.pinyin}
Meaning: ${detail.meaning}
Etymology: ${detail.etymology}
`).join('\n')}

--------------------------------------------------------------------------------
                           CULTURAL RESONANCE
--------------------------------------------------------------------------------

${name.culturalResonance}

--------------------------------------------------------------------------------
                              SAFETY AUDIT
--------------------------------------------------------------------------------

Tattoo Application: ${name.safetyAudit.tattoo}
Business Usage: ${name.safetyAudit.business}
Digital Presence: ${name.safetyAudit.digital}

================================================================================
                              CHARACTER GRID
================================================================================

The grid below shows the proper stroke order for each character.

${strokeGrid}

================================================================================
                               DISCLAIMER
================================================================================

This report is generated by CINNABAR - Authentic Chinese Naming Service.
All names are verified for cultural safety and appropriateness.
For questions or concerns, please contact our support team.

© 2026 CINNABAR. Wisdom in Every Stroke.

================================================================================
`;
}

function generateStrokeGrid(characters: string): string {
  // 生成米字格模板
  const grids = characters.split('').map(char => {
    return `
    ┌─────────────────────────────────┐
    │                                 │
    │           ╱     ╲               │
    │          ╱   ${char}    ╲              │
    │         ╱    ╱╲    ╲             │
    │        ╱   ╱  ╲    ╲            │
    │       │    │  │    │            │
    │        ╲   ╲  ╱    ╱            │
    │         ╲   ╲╱    ╱             │
    │          ╲   │   ╱              │
    │           ╲     ╱               │
    │            ─────                │
    │                                 │
    └─────────────────────────────────┘
    Character: ${char}`;
  });

  return grids.join('\n');
}

// 前端 PDF 下载支持
export function createPDFFile(data: ReportData): Blob {
  const content = generatePDFContent(data);
  return new Blob([content], { type: 'text/plain' });
}

export function downloadPDF(data: ReportData, filename: string = 'cinnabar-report.pdf'): void {
  const blob = createPDFFile(data);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
